export const PLATFORM_RESOURCE_BOT_SETTINGS_ID =
  "00000000-0000-4000-8000-000000000031";

export const RESOURCE_BOT_DEFAULT_PROVIDER = "OpenAI";
export const RESOURCE_BOT_DEFAULT_GENERATION_MODEL = "gpt-5.6-luna";
export const RESOURCE_BOT_DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small";
export const RESOURCE_BOT_MAX_OUTPUT_TOKENS = 700;
export const RESOURCE_BOT_MAX_QUESTION_LENGTH = 4_000;
export const RESOURCE_BOT_MAX_HISTORY_TURNS = 6;
