import { forwardRef, type InputHTMLAttributes, type SelectHTMLAttributes, type TextareaHTMLAttributes, type ReactNode } from "react";
import { SearchIcon } from "./icons";
import { cx } from "./primitives";

export function Field({ label, hint, error, required, children, className }: { label: string; hint?: ReactNode; error?: ReactNode; required?: boolean; children: ReactNode; className?: string }) { return <label className={cx("block min-w-0", className)}><span className="mb-1.5 block text-[13px] font-medium text-[#172033]">{label}{required ? <span className="ml-1 text-[#C42B1C]" aria-hidden="true">*</span> : null}</span>{children}{error ? <span className="mt-1 block text-xs text-[#C42B1C]">{error}</span> : hint ? <span className="mt-1 block text-xs leading-4 text-[#718096]">{hint}</span> : null}</label>; }
const inputClass = "h-10 w-full rounded-md border border-[#B9C5D6] bg-white px-3 text-sm text-[#172033] shadow-[0_1px_1px_rgba(16,24,40,.02)] outline-none placeholder:text-[#8A96A8] focus:border-[#1769E0] focus:ring-2 focus:ring-[#1769E0]/15 disabled:bg-[#F3F5F8] disabled:text-[#7B8798]";
export const TextInput = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(function TextInput({ className, ...props }, ref) { return <input ref={ref} className={cx(inputClass, className)} {...props}/>; });
export const NumberInput = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(function NumberInput({ className, ...props }, ref) { return <input ref={ref} type="number" className={cx(inputClass, className)} {...props}/>; });
export const Checkbox = forwardRef<HTMLInputElement, Omit<InputHTMLAttributes<HTMLInputElement>, "type">>(function Checkbox({ className, ...props }, ref) { return <input ref={ref} type="checkbox" className={cx("rp-checkbox", className)} {...props}/>; });
export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(function Select({ className, children, ...props }, ref) { return <select ref={ref} className={cx(inputClass, "appearance-none bg-[linear-gradient(45deg,transparent_50%,#667085_50%),linear-gradient(135deg,#667085_50%,transparent_50%)] bg-[position:calc(100%-16px)_17px,calc(100%-12px)_17px] bg-[size:4px_4px,4px_4px] bg-no-repeat pr-9", className)} {...props}>{children}</select>; });
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(function Textarea({ className, ...props }, ref) { return <textarea ref={ref} className={cx("min-h-24 w-full resize-y rounded-md border border-[#B9C5D6] bg-white px-3 py-2.5 text-sm leading-5 text-[#172033] outline-none placeholder:text-[#8A96A8] focus:border-[#1769E0] focus:ring-2 focus:ring-[#1769E0]/15 disabled:bg-[#F3F5F8]", className)} {...props}/>; });
export function SearchField({ value, onChange, placeholder = "Search", ariaLabel = "Search" }: { value: string; onChange: (value: string) => void; placeholder?: string; ariaLabel?: string }) { return <div className="relative min-w-0 flex-1 sm:max-w-[330px]"><SearchIcon size={17} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#718096]"/><input aria-label={ariaLabel} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className={cx(inputClass, "pl-9")}/></div>; }
export function Toggle({ checked, onChange, label, description, disabled }: { checked: boolean; onChange: (checked: boolean) => void; label: string; description?: string; disabled?: boolean }) { return <label className="flex cursor-pointer items-start gap-3"><input className="peer sr-only" type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} disabled={disabled}/><span className="relative mt-0.5 h-5 w-9 shrink-0 rounded-full bg-[#AAB5C4] transition peer-checked:bg-[#1769E0] peer-focus-visible:outline peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-[#1769E0] peer-disabled:opacity-50 after:absolute after:left-0.5 after:top-0.5 after:h-4 after:w-4 after:rounded-full after:bg-white after:shadow after:transition peer-checked:after:translate-x-4"/><span><strong className="block text-[13px] font-medium text-[#172033]">{label}</strong>{description ? <span className="mt-0.5 block text-xs text-[#718096]">{description}</span> : null}</span></label>; }
export function Stepper({ steps, current }: { steps: string[]; current: number }) { return <ol className="flex w-full max-w-full min-w-0 items-start overflow-x-auto pb-2 overscroll-x-contain [contain:layout_paint]" aria-label="Creation steps">{steps.map((step, index) => { const complete = index < current; const active = index === current; return <li key={step} aria-current={active ? "step" : undefined} className="flex min-w-[132px] flex-1 items-start sm:min-w-[140px] xl:min-w-[150px] last:flex-none"><div className="flex min-w-0 flex-1 items-center"><span className={cx("flex h-7 w-7 shrink-0 items-center justify-center rounded-full border text-xs font-semibold", complete ? "border-[#137A4A] bg-[#137A4A] text-white" : active ? "border-[#1769E0] bg-[#1769E0] text-white" : "border-[#C7D1DF] bg-white text-[#718096]")}>{complete ? "✓" : index + 1}</span><span className={cx("ml-2 whitespace-nowrap text-[12px] font-medium", active ? "text-[#172033]" : complete ? "text-[#137A4A]" : "text-[#718096]")}>{step}</span>{index < steps.length - 1 ? <span className={cx("mx-3 h-px flex-1", complete ? "bg-[#78C79F]" : "bg-[#D7E0EC]")}/> : null}</div></li>; })}</ol>; }