Log:
  Level: info

Port: 8080
ExternalDomain: localhost
ExternalPort: 8080
ExternalSecure: false

TLS:
  Enabled: false

Database:
  postgres:
    Host: zitadel-postgres
    Port: 5432
    Database: zitadel
    User:
      SSL:
        Mode: disable
    Admin:
      SSL:
        Mode: disable
