import { useMemo, useState } from "react";
import { apiRequest } from "../../api/client";
import { Button, Card, DataTable, Dialog, EmptyState, GridIcon, LinkButton, MoreIcon, PlusIcon, ResourceMark, SearchField, StatusText, statusTone } from "../../components/design-system";
import { appGroupHref } from "../../router/router";
import { formatBytes, items, text, useApi } from "../../hooks/use-api";

export function AppGroupApps({ tenantId, appGroupId }: { tenantId: string; appGroupId: string }) {
  const root = `/api/tenants/${encodeURIComponent(tenantId)}/app-groups/${encodeURIComponent(appGroupId)}`; const { data, loading, error, reload } = useApi<unknown>(`${root}/single-apps`); const apps = items<Record<string,unknown>>(data); const [query,setQuery]=useState(""); const [deleteApp,setDeleteApp]=useState<Record<string,unknown>>(); const [busy,setBusy]=useState<string>(); const [actionError,setActionError]=useState<string>();
  const visible=useMemo(()=>apps.filter(a=>text(a.name,"").toLowerCase().includes(query.toLowerCase())),[apps,query]);
  async function runtime(app:Record<string,unknown>,action:"start"|"stop"|"restart"){const id=text(app.id,"");setBusy(`${id}:${action}`);setActionError(undefined);try{await apiRequest(`${root}/single-apps/${encodeURIComponent(id)}/runtime/${action}`,{method:"POST"});await reload();}catch(cause){setActionError(cause instanceof Error?cause.message:"Runtime action failed.");}finally{setBusy(undefined);}}
  async function remove(){if(!deleteApp)return;const id=text(deleteApp.id,"");setBusy(`${id}:delete`);setActionError(undefined);try{await apiRequest(`${root}/single-apps/${encodeURIComponent(id)}`,{method:"DELETE"});setDeleteApp(undefined);await reload();}catch(cause){setActionError(cause instanceof Error?cause.message:"Delete failed.");}finally{setBusy(undefined);}}
  const rows=visible.map(app=>{const id=text(app.id,"");const runtimeState=text(app.effectiveRuntimeState,app.runtimeState as string);const replicas=String(app.effectiveReplicas??app.desiredReplicas??0);return {key:id,href:appGroupHref(tenantId,appGroupId,`apps/${id}`),cells:{name:<span className="flex items-center gap-3"><ResourceMark><GridIcon size={15}/></ResourceMark><span><strong className="block">{text(app.name,"Application")}</strong><span className="block max-w-[260px] truncate text-[11px] font-normal text-[#718096]">{text(app.image,"No image")}</span></span></span>,runtime:<StatusText tone={statusTone(runtimeState)}>{runtimeState}</StatusText>,replicas,cpu:`${text(app.cpu,"0")} CPU`,memory:formatBytes(app.memoryBytes),health:<StatusText tone={statusTone(app.health)}>{text(app.health,"Unknown")}</StatusText>,actions:<div className="flex items-center justify-end gap-1"><Button size="sm" variant="ghost" disabled={Boolean(busy)} onClick={(e)=>{e.preventDefault();void runtime(app,runtimeState.toLowerCase()==="running"?"stop":"start")}}>{runtimeState.toLowerCase()==="running"?"Stop":"Start"}</Button><a href={appGroupHref(tenantId,appGroupId,`apps/${id}/edit`)} aria-label={`Edit ${text(app.name,"application")}`} className="inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-[#EEF3F9]"><MoreIcon size={16}/></a><button aria-label={`Delete ${text(app.name,"application")}`} className="sr-only" onClick={()=>setDeleteApp(app)}>Delete</button></div>}}});
  return <section><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[12px] font-semibold uppercase tracking-[.03em] text-[#1769E0]">Applications</p><h2 className="text-xl font-semibold">Apps</h2><p className="mt-1 text-sm text-[#5B6678]">Containers deployed together as part of this App Group.</p></div><LinkButton variant="primary" href={appGroupHref(tenantId,appGroupId,"apps/new")}><PlusIcon size={16}/>Create application</LinkButton></div>{actionError?<div className="mb-4 rounded-lg border border-[#E4A9A3] bg-[#FFF3F2] px-4 py-3 text-sm text-[#A92317]">{actionError}</div>:null}<Card className="overflow-hidden"><div className="border-b border-[#E1E7F0] px-4 py-3"><SearchField value={query} onChange={setQuery} placeholder="Search applications" ariaLabel="Search applications"/></div>{error?<div className="p-5 text-sm text-[#C42B1C]">Applications could not be loaded.</div>:<DataTable embedded className="rounded-none border-0" loading={loading} columns={[{key:"name",label:"Application"},{key:"runtime",label:"Runtime"},{key:"replicas",label:"Replicas"},{key:"cpu",label:"CPU"},{key:"memory",label:"Memory"},{key:"health",label:"Health"},{key:"actions",label:""}]} rows={rows} empty={<EmptyState icon={<GridIcon/>} title="No applications" description="Create the first application in this App Group." action={<LinkButton variant="primary" href={appGroupHref(tenantId,appGroupId,"apps/new")}><PlusIcon/>Create application</LinkButton>}/>} footer={visible.length?`${visible.length} application${visible.length===1?"":"s"}`:undefined}/>}</Card><Dialog open={Boolean(deleteApp)} onClose={()=>setDeleteApp(undefined)} title="Delete application?" danger description="The application will be marked for deletion in the App Group draft. Deploy changes to apply the deletion." actions={<><Button onClick={()=>setDeleteApp(undefined)}>Cancel</Button><Button variant="danger" disabled={Boolean(busy)} onClick={()=>void remove()}>Delete application</Button></>}>{deleteApp?<p className="text-sm">Delete <strong>{text(deleteApp.name,"this application")}</strong> from the deployment workspace?</p>:null}</Dialog></section>;
}
