import { useState } from "react";
import { apiRequest } from "../../api/client";
import { Button, Card, ConfirmActionButton, DataTable, EmptyState, Field, FileIcon, KeyIcon, LockIcon, PlusIcon, Select, Textarea, TextInput, TrashIcon } from "../../components/design-system";
import { toast } from "../../components/toast";
import { idOf, items, text, useApi } from "../../hooks/use-api";

type Kind = "variables" | "secrets" | "configs";
type Item = Record<string, unknown>;
const meta = {
  variables: { title: "Variables", description: "Reusable non-sensitive values exposed to applications by attachment.", icon: <KeyIcon size={18}/> },
  secrets: { title: "Secrets", description: "Sensitive values. Secret contents are never shown after creation.", icon: <LockIcon size={18}/> },
  configs: { title: "Configs", description: "Reusable configuration files attached to application paths.", icon: <FileIcon size={18}/> },
} as const;

function ResourcePanel({ root, kind }: { root: string; kind: Kind }) {
  const query = useApi<unknown>(`${root}/${kind}`); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Item>(); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [value,setValue]=useState(""); const [type,setType]=useState("Text"); const [fileName,setFileName]=useState(""); const [working,setWorking]=useState(false);
  const rows=items<Item>(query.data);
  function begin(item?: Item){setEditing(item);setName(text(item?.name,""));setDescription(text(item?.description,""));setValue(kind==="variables"?text(item?.value,""):kind==="configs"?text(item?.content,""):"");setType(text(item?.type,"Text"));setFileName(text(item?.fileName,""));setOpen(true);}
  async function save(){if(!name.trim())return;setWorking(true);try{let body:Record<string,unknown>;if(kind==="variables")body={name,description:description||undefined,value};else if(kind==="secrets")body={name,description:description||undefined,type,fileName:fileName||undefined,...(!editing||value?{value}: {})};else body={name,description:description||undefined,content:value};const id=editing?idOf(editing):"";await apiRequest(`${root}/${kind}${id?`/${encodeURIComponent(id)}`:""}`,{method:id?"PATCH":"POST",body});setOpen(false);await query.reload();toast.success(`${kind.slice(0,-1)} ${id?"updated":"created"}.`);}catch(cause){toast.errorFrom(cause,"The request could not be completed.");}finally{setWorking(false);}}
  async function remove(item:Item){try{await apiRequest(`${root}/${kind}/${encodeURIComponent(idOf(item))}`,{method:"DELETE"});await query.reload();toast.success(`${kind.slice(0,-1)} deleted.`);}catch(cause){toast.errorFrom(cause,"Delete failed.");}}
  const m=meta[kind];
  return <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#E1E7F0] px-5 py-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="mt-0.5 text-[#1769E0]">{m.icon}</span><div><h3 className="text-base font-semibold">{m.title}</h3><p className="mt-0.5 text-[13px] text-[#5B6678]">{m.description}</p></div></div><Button size="sm" onClick={()=>begin()}><PlusIcon size={15}/>Add</Button></div>{open?<div className="grid gap-4 border-b border-[#E1E7F0] bg-[#F8FAFD] p-5 md:grid-cols-2"><Field label="Name" required><TextInput value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Description"><TextInput value={description} onChange={e=>setDescription(e.target.value)}/></Field>{kind==="secrets"?<><Field label="Type"><Select value={type} onChange={e=>setType(e.target.value)}><option value="Text">Text</option><option value="Binary">Binary</option></Select></Field>{type==="Binary"?<Field label="File name"><TextInput value={fileName} onChange={e=>setFileName(e.target.value)}/></Field>:null}</>:null}<div className="md:col-span-2"><Field label={kind==="configs"?"Content":kind==="secrets"?(editing?"New value (optional)":"Value"):"Value"} required={!editing||kind!=="secrets"}><Textarea value={value} onChange={e=>setValue(e.target.value)} className="min-h-28"/></Field></div><div className="flex gap-2 md:col-span-2"><Button variant="primary" disabled={working||!name.trim()} onClick={()=>void save()}>{working?"Saving…":editing?"Save changes":"Create"}</Button><Button onClick={()=>setOpen(false)}>Cancel</Button></div></div>:null}<DataTable embedded loading={query.loading} columns={[{key:"name",label:"Name"},{key:"description",label:"Description"},{key:"updated",label:"Updated"},{key:"actions",label:""}]} rows={rows.map(item=>({key:idOf(item),cells:{name:<strong>{text(item.name)}</strong>,description:text(item.description,"—"),updated:text(item.updatedAt,item.createdAt as string),actions:<div className="flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={()=>begin(item)}>Edit</Button><ConfirmActionButton size="sm" triggerVariant="ghost" ariaLabel={`Delete ${text(item.name)}`} confirmTitle={`Delete ${text(item.name,"this item")}?`} confirmDescription={`This permanently deletes the ${kind.slice(0,-1)} from this App Group.`} confirmLabel={`Delete ${kind.slice(0,-1)}`} onConfirm={()=>remove(item)}><TrashIcon size={15}/></ConfirmActionButton></div>}}))} empty={<EmptyState title={`No ${m.title.toLowerCase()} yet`} description={`Create the first ${m.title.slice(0,-1).toLowerCase()} for this App Group.`}/>}/></Card>;
}

export function AppGroupConfig({ tenantId, appGroupId }: { tenantId:string; appGroupId:string }) { const root=`/api/tenants/${encodeURIComponent(tenantId)}/app-groups/${encodeURIComponent(appGroupId)}`; return <section className="space-y-4"><div><h2 className="text-xl font-semibold">Configuration</h2><p className="mt-1 text-sm text-[#5B6678]">Manage reusable variables, secrets and configs without exposing backend-oriented payloads.</p></div><ResourcePanel root={root} kind="variables"/><ResourcePanel root={root} kind="secrets"/><ResourcePanel root={root} kind="configs"/></section>; }
