import { useState } from "react";
import { apiRequest } from "../../api/client";
import { Button, Callout, Card, ConfirmActionButton, DataTable, DeployIcon, EmptyState, Field, HistoryIcon, StatusText, Textarea, statusTone } from "../../components/design-system";
import { formatDate, idOf, items, text, useApi } from "../../hooks/use-api";

type R=Record<string,unknown>;
export function AppGroupDeployments({tenantId,appGroupId,onReload}:{tenantId:string;appGroupId:string;onReload:()=>Promise<unknown>}){
 const root=`/api/tenants/${encodeURIComponent(tenantId)}/app-groups/${encodeURIComponent(appGroupId)}`; const q=useApi<unknown>(`${root}/deployments`); const [note,setNote]=useState(""); const [working,setWorking]=useState<string>(); const [error,setError]=useState<string>(); const [selected,setSelected]=useState<R>(); const events=useApi<unknown>(selected?`${root}/deployments/${encodeURIComponent(idOf(selected))}/events`:undefined);
 async function deploy(){setWorking("deploy");setError(undefined);try{await apiRequest(`${root}/deploy`,{method:"POST",body:note?{note}:{}});setNote("");await Promise.all([q.reload(),onReload()]);}catch(c){setError(c instanceof Error?c.message:"Deployment failed.");}finally{setWorking(undefined);}}
 async function rollback(item:R){setWorking(idOf(item));setError(undefined);try{await apiRequest(`${root}/deployments/${encodeURIComponent(idOf(item))}/rollback`,{method:"POST",body:{note:`Rollback to deployment ${text(item.version,idOf(item))}`}});await Promise.all([q.reload(),onReload()]);}catch(c){setError(c instanceof Error?c.message:"Rollback failed.");}finally{setWorking(undefined);}}
 const rows=items<R>(q.data);
 return <section className="space-y-4"><div><h2 className="text-xl font-semibold">Deployments</h2><p className="mt-1 text-sm text-[#5B6678]">Publish pending workspace changes, inspect deployment history and roll back when required.</p></div>{error?<Callout tone="danger" title="Deployment action failed">{error}</Callout>:null}<Card className="p-5"><div className="grid gap-4 md:grid-cols-[1fr_auto] md:items-end"><Field label="Deployment note" hint="Optional context for this release."><Textarea className="min-h-20" value={note} onChange={e=>setNote(e.target.value)} placeholder="Describe the change being deployed."/></Field><Button variant="primary" disabled={Boolean(working)} onClick={()=>void deploy()}><DeployIcon size={16}/>{working==="deploy"?"Deploying…":"Deploy pending changes"}</Button></div></Card><Card className="overflow-hidden"><DataTable embedded loading={q.loading} columns={[{key:"version",label:"Version"},{key:"status",label:"Status"},{key:"note",label:"Note"},{key:"time",label:"Timestamp"},{key:"actions",label:""}]} rows={rows.map(d=>({key:idOf(d),cells:{version:<strong>{d.version==null?text(d.name,"Deployment"):`v${text(d.version)}`}</strong>,status:<StatusText tone={statusTone(d.status)}>{text(d.status,"Unknown")}</StatusText>,note:text(d.note,"—"),time:formatDate(d.createdAt??d.updatedAt),actions:<div className="flex justify-end gap-1"><Button size="sm" variant="ghost" onClick={()=>setSelected(d)}>Inspect</Button><ConfirmActionButton size="sm" triggerVariant="ghost" disabled={Boolean(working)} confirmTitle={`Rollback deployment v${text(d.version,idOf(d))}?`} confirmDescription="Rollback creates a new deployment from this previous version and changes the active workload configuration." confirmLabel={`Rollback to v${text(d.version,idOf(d))}`} onConfirm={()=>rollback(d)}>Rollback</ConfirmActionButton></div>}}))} empty={<EmptyState icon={<HistoryIcon/>} title="No deployments yet" description="Deploy the current workspace to create the first version."/>}/></Card>{selected?<Card className="overflow-hidden"><div className="border-b border-[#E1E7F0] px-5 py-4"><h3 className="font-semibold">Deployment events</h3><p className="text-xs text-[#718096]">{selected.version==null?text(selected.name,"Deployment"):`Version ${text(selected.version)}`}</p></div><div className="divide-y divide-[#E1E7F0]">{events.loading?<p className="p-5 text-sm text-[#5B6678]">Loading events…</p>:items<R>(events.data).length?items<R>(events.data).map(e=><div className="grid gap-1 px-5 py-3 md:grid-cols-[160px_1fr_160px]" key={idOf(e)||`${text(e.type)}-${text(e.createdAt)}`}><strong className="text-[13px]">{text(e.type,"Event")}</strong><span className="text-[13px] text-[#526070]">{text(e.message,text(e.detail,"—"))}</span><span className="text-xs text-[#718096]">{formatDate(e.createdAt)}</span></div>):<p className="p-5 text-sm text-[#5B6678]">No events recorded for this deployment.</p>}</div></Card>:null}</section>;
}
