import { useState, type ReactNode } from "react";
import { apiRequest } from "../../api/client";
import { appGroupHref, tenantHref } from "../../router/router";
import { Button, Callout, DeployIcon, GridIcon, LinkButton, PageHeader, PlayIcon, RestartIcon, StatusBadge, StopIcon, Tabs, Tooltip, statusTone } from "../../components/design-system";
import { text } from "../../hooks/use-api";
import { toast } from "../../components/toast";

export type AppGroupRecord = Record<string, unknown>;

function blockers(value: unknown) { return Array.isArray(value) ? value.map(String) : []; }
function blockerCopy(code: string) { if (code === "BillingSuspended") return "The tenant balance is empty. Add credits before starting workloads."; if (code === "TenantSuspended") return "This tenant is suspended. Runtime operations are blocked."; if (code === "PlatformMaintenance") return "Platform maintenance is active. Runtime changes are temporarily blocked."; if (code === "AppGroupNotDeployed") return "Deploy the current workspace before starting this App Group."; if (code === "AppGroupError") return "The App Group is in an error state. Review the latest deployment and activity."; if (code === "AppGroupDeleting") return "This App Group is being deleted."; return code; }

function StatusSummaryBadge({ label, value, help }: { label: string; value: string; help: string }) {
  return <Tooltip content={help}><StatusBadge tone={statusTone(value)} className="min-h-8 gap-2 px-3 shadow-[0_1px_2px_rgba(15,23,42,0.04)] transition duration-150 group-hover:-translate-y-px group-hover:shadow-md group-focus-within:shadow-md"><span className="text-[10px] font-semibold uppercase tracking-[0.045em] opacity-70">{label}</span><span aria-hidden="true" className="h-3 w-px bg-current opacity-20"/><span className="font-semibold tracking-[-0.01em]">{value}</span></StatusBadge></Tooltip>;
}

export function AppGroupLayout({ tenantId, group, section, onReload, children }: { tenantId: string; group: AppGroupRecord; section: string; onReload: () => Promise<unknown>; children: ReactNode }) {
  const id = text(group.id, ""); const name = text(group.name, "App Group"); const desired = text(group.runtimeState, "Unknown"); const effective = text(group.effectiveRuntimeState, desired); const health = text(group.health, "Unknown"); const drift = text(group.driftStatus, "Unknown"); const pending = group.hasPendingChanges === true; const runtimeBlockers = blockers(group.runtimeBlockers).filter(x => x !== "AppGroupStopped");
  const [working, setWorking] = useState<string>();
  async function action(kind: "start"|"stop"|"restart"|"deploy") { setWorking(kind); try { await apiRequest(`/api/tenants/${encodeURIComponent(tenantId)}/app-groups/${encodeURIComponent(id)}/${kind === "deploy" ? "deploy" : `runtime/${kind}`}`, { method: "POST", body: kind === "deploy" ? {} : undefined }); await onReload(); toast.success(kind === "deploy" ? "Deployment requested." : `App Group ${kind} requested.`); } catch (cause) { toast.errorFrom(cause, `Unable to ${kind}.`); } finally { setWorking(undefined); } }
  const tabs = ["overview","apps","config","networking","deployments","activity"].map(key => ({ label: key[0].toUpperCase()+key.slice(1), href: key === "overview" ? appGroupHref(tenantId,id) : appGroupHref(tenantId,id,key), active: section === key }));
  return <main><PageHeader eyebrow="App Group" title={<span className="flex items-start gap-3"><span className="mt-1 flex h-[52px] w-[52px] shrink-0 items-center justify-center rounded-xl bg-[#E7F1FF] text-[#1769E0]"><GridIcon size={22}/></span><span><span className="block">{name}</span><span className="mt-2 inline-flex max-w-full flex-wrap items-center gap-1.5 rounded-xl border border-[#DCE4EF] bg-[#F8FAFD] p-1.5 shadow-[inset_0_1px_0_rgba(255,255,255,0.75)]"><StatusSummaryBadge label="Runtime" value={effective} help="Effective runtime state after tenant, billing and platform blockers are applied. Running means the App Group is configured to run and no runtime blocker is forcing it to Stopped."/><StatusSummaryBadge label="Health" value={health} help="Health compares expected replicas with the workloads observed in the runtime. Healthy means every app has the expected number of running replicas."/><StatusSummaryBadge label="Sync" value={drift.toLowerCase() === "insync" ? "In sync" : drift} help="Sync compares the deployed service set, images and desired replica counts with the runtime. In sync means they match the expected deployment."/>{pending ? <StatusSummaryBadge label="Draft" value="Pending changes" help="Pending changes means this workspace contains edits that are not part of the current deployed revision yet. Deploy changes to publish them."/> : null}</span></span></span>} description={text(group.description, "Application deployment workspace")} breadcrumbs={<><a href={tenantHref(tenantId,"applications")} className="hover:underline">Applications</a><span className="mx-1.5">/</span>{name}</>} actions={<><Button onClick={()=>void action(effective.toLowerCase()==="running"?"stop":"start")} disabled={Boolean(working) || (effective.toLowerCase()!=="running" && runtimeBlockers.length>0)}>{effective.toLowerCase()==="running" ? <><StopIcon size={16}/>Stop</> : <><PlayIcon size={16}/>Start</>}</Button><Button onClick={()=>void action("restart")} disabled={Boolean(working) || effective.toLowerCase()!=="running"}><RestartIcon size={16}/>Restart</Button><Button variant="primary" onClick={()=>void action("deploy")} disabled={Boolean(working) || !pending}><DeployIcon size={16}/>{working === "deploy" ? "Deploying…" : "Deploy changes"}</Button></>}/>
    {runtimeBlockers.length ? <div className="mb-4"><Callout tone="warning" title="Runtime action blocked" action={runtimeBlockers.includes("BillingSuspended") ? <LinkButton href={tenantHref(tenantId,"billing")} variant="ghost" className="h-8 border-0 px-2">Add credits</LinkButton> : undefined}>{runtimeBlockers.map(blockerCopy).join(" ")}</Callout></div> : null}
    {pending ? <div className="mb-4"><Callout tone="warning" title="Changes are waiting to be deployed" action={<a href={appGroupHref(tenantId,id,"deployments")} className="hover:underline">Review deployment</a>}>Review the deployment section when you are ready to publish them.</Callout></div> : null}
    <Tabs items={tabs} label="App Group sections"/>{children}
  </main>;
}