#!/usr/bin/env node
import {readFileSync,writeFileSync} from 'node:fs';
import {collectMatrix,listTests} from './test-catalog.mjs';
const suites=JSON.parse(readFileSync(new URL('../config/test-suites.json',import.meta.url),'utf8')).suites;
const paths=listTests();
const matrix=collectMatrix(paths);
const levels=['unit','component','contract','integration','system','e2e','security','upgrade','packaging'];
const lines=[
  '# ResourcePortal test matrix',
  '',
  'Generated by `node scripts/test-matrix.mjs --write`. Counts below represent matching **files**, not assertion count, coverage or successful runs.',
  '',
  '| Domain | '+levels.join(' | ')+' | Total |',
  '|---|'+levels.map(()=> '---:|').join('')+'---:|',
];
for(const domain of Object.keys(matrix).sort()){
  const row=levels.map(level=>matrix[domain][level]||0);
  lines.push('| '+domain+' | '+row.join(' | ')+' | '+row.reduce((a,b)=>a+b,0)+' |');
}
lines.push('','Total detected test files: **'+paths.length+'**.','', '## Execution suites','','| Suite | Level | Domain | Environment |', '|---|---|---|---|');
for(const s of suites)lines.push('| '+s.id+' | '+s.level+' | '+s.domain+' | '+(s.workflow||s.environment)+' |');
lines.push('','Folders are migration-neutral: unit tests remain colocated with implementation. Infrastructure E2E and integration checks are listed by their workflow, not counted as individual test files.','');
const desired=lines.join('\n');
const target=new URL('../docs/testing/TEST_MATRIX.md',import.meta.url);
if(process.argv.includes('--write'))writeFileSync(target,desired);
else if(process.argv.includes('--check')){
  if(readFileSync(target,'utf8')!==desired){console.error('Test matrix has drifted: run node scripts/test-matrix.mjs --write');process.exitCode=1;}
}else console.log(desired);
