import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../api/client";
import { appGroupHref, tenantHref } from "../router/router";
import { Card, DataTable, EmptyState, GridIcon, LinkButton, MetricCard, MoreIcon, PageHeader, PlusIcon, ResourceMark, SearchField, Select, StatusText, statusTone } from "../components/design-system";

type Group = Record<string, unknown>;
function list(value: unknown): Group[] { if (Array.isArray(value)) return value.filter((x): x is Group => !!x && typeof x === "object"); if (value && typeof value === "object") { const v = value as Group; for (const key of ["items", "data", "results"]) if (Array.isArray(v[key])) return list(v[key]); } return []; }
function text(value: unknown, fallback = "—") { return typeof value === "string" && value ? value : fallback; }
function countApps(group: Group) { return Array.isArray(group.singleApps) ? group.singleApps.length : typeof group.appCount === "number" ? group.appCount : 0; }
function relative(value: unknown) { if (typeof value !== "string") return "—"; const time = Date.parse(value); if (!Number.isFinite(time)) return value; const delta = Date.now() - time; const min = Math.max(0, Math.floor(delta / 60000)); if (min < 1) return "Just now"; if (min < 60) return `${min} min ago`; const h = Math.floor(min / 60); if (h < 24) return `${h} h ago`; const d = Math.floor(h / 24); return d === 1 ? "Yesterday" : `${d} d ago`; }

export function ApplicationsPage({ tenantId }: { tenantId: string }) {
  const [groups, setGroups] = useState<Group[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>(); const [search, setSearch] = useState(""); const [state, setState] = useState("all"); const [health, setHealth] = useState("all");
  useEffect(() => { let active = true; setLoading(true); apiRequest(`/api/tenants/${encodeURIComponent(tenantId)}/app-groups`).then(value => { if (active) { setGroups(list(value)); setLoading(false); } }).catch(cause => { if (active) { setError(cause); setLoading(false); } }); return () => { active = false; }; }, [tenantId]);
  const filtered = useMemo(() => groups.filter(group => { const name = text(group.name, "").toLowerCase(); const runtime = text(group.effectiveRuntimeState, text(group.runtimeState, "unknown")).toLowerCase(); const h = text(group.health, "unknown").toLowerCase(); return name.includes(search.toLowerCase()) && (state === "all" || runtime === state) && (health === "all" || h === health); }), [groups, search, state, health]);
  const running = groups.filter(group => text(group.effectiveRuntimeState, group.runtimeState as string).toLowerCase() === "running").length; const appCount = groups.reduce((sum, g) => sum + countApps(g), 0); const attention = groups.filter(g => statusTone(g.health) === "danger" || g.hasPendingChanges === true).length;
  const rows = filtered.map(group => { const id = String(group.id ?? ""); const runtime = text(group.effectiveRuntimeState, group.runtimeState as string); const groupHealth = text(group.health, "Unknown"); const deployment = group.currentDeploymentVersion == null ? "—" : `v${String(group.currentDeploymentVersion)}`; const apps = countApps(group); return { key: id, href: appGroupHref(tenantId, id), cells: { name: <span className="flex items-center gap-3"><ResourceMark><GridIcon size={16}/></ResourceMark><span><span className="block font-semibold text-[#172033]">{text(group.name, "Unnamed App Group")}</span><span className="mt-0.5 block text-[11px] font-normal text-[#718096]">App Group</span></span></span>, apps: `${apps} app${apps === 1 ? "" : "s"}`, runtime: <StatusText tone={statusTone(runtime)}>{runtime}</StatusText>, health: <StatusText tone={statusTone(groupHealth)}>{groupHealth}</StatusText>, deployment, changes: <StatusText tone={group.hasPendingChanges === true ? "warning" : "neutral"}>{group.hasPendingChanges === true ? "Pending changes" : "Up to date"}</StatusText>, updated: relative(group.updatedAt ?? group.createdAt), action: <a aria-label={`Open ${text(group.name, "App Group")}`} href={appGroupHref(tenantId, id)} className="inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-[#EEF3F9]"><MoreIcon size={17}/></a> } }; });
  return <main>
    <PageHeader eyebrow="Workloads" title="Applications" description="Manage App Groups and the applications they contain." breadcrumbs={<><a className="hover:underline" href={tenantHref(tenantId, "overview")}>Tenant</a><span className="mx-1.5">/</span>Applications</>} actions={<LinkButton variant="primary" href={tenantHref(tenantId, "applications", "new")}><GridIcon size={16}/>Create App Group</LinkButton>}/>
    <section className="mb-5 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Application summary"><MetricCard label="App Groups" value={groups.length} detail={`${appCount} apps configured`} loading={loading} error={error}/><MetricCard label="Running" value={running} detail={`${Math.max(0, groups.length-running)} not running`} tone="success" loading={loading} error={error}/><MetricCard label="Apps configured" value={appCount} detail={`Across ${groups.length} App Groups`} loading={loading} error={error}/><MetricCard label="Needs attention" value={attention} detail="Review runtime blockers" tone={attention ? "warning" : "success"} loading={loading} error={error}/></section>
    <Card className="overflow-hidden"><div className="px-5 py-4"><h2 className="text-base font-semibold text-[#172033]">App Groups</h2><p className="mt-0.5 text-[13px] text-[#5B6678]">Deployment boundaries containing one or more applications.</p></div><div className="flex flex-col gap-2 border-y border-[#E1E7F0] px-5 py-3 sm:flex-row sm:items-center"><SearchField value={search} onChange={setSearch} placeholder="Search App Groups" ariaLabel="Search App Groups"/><Select aria-label="Filter by state" value={state} onChange={e => setState(e.target.value)} className="sm:w-[150px]"><option value="all">State: All</option><option value="running">Running</option><option value="stopped">Stopped</option></Select><Select aria-label="Filter by health" value={health} onChange={e => setHealth(e.target.value)} className="sm:w-[160px]"><option value="all">Health: All</option><option value="healthy">Healthy</option><option value="warning">Warning</option><option value="unhealthy">Unhealthy</option><option value="unknown">Unknown</option></Select><span className="ml-auto whitespace-nowrap text-xs text-[#5B6678]">{filtered.length} App Group{filtered.length === 1 ? "" : "s"}</span></div>
    {error ? <div className="p-5 text-sm text-[#C42B1C]">Applications could not be loaded. Refresh the page to retry.</div> : <DataTable className="rounded-none border-0" loading={loading} columns={[{key:"name",label:"App Group"},{key:"apps",label:"Apps"},{key:"runtime",label:"Runtime"},{key:"health",label:"Health"},{key:"deployment",label:"Deployment"},{key:"changes",label:"Changes"},{key:"updated",label:"Updated"},{key:"action",label:""}]} rows={rows} empty={<EmptyState icon={<GridIcon/>} title="No App Groups match these filters" description="Clear filters or create an App Group to start deploying applications." action={<LinkButton variant="primary" href={tenantHref(tenantId,"applications","new")}><PlusIcon/>Create App Group</LinkButton>}/>} footer={filtered.length ? `1–${filtered.length} of ${filtered.length}` : undefined}/>}</Card>
  </main>;
}
