import { useMemo, useState } from "react";
import { apiRequest } from "../api/client";
import { ActivityIcon, Button, Callout, Card, DataTable, EmptyState, Field, PageHeader, SearchIcon, Select, StatusText, TextInput, statusTone } from "../components/design-system";
import { formatDate, idOf, items, text, useApi } from "../hooks/use-api";
import { tenantHref } from "../router/router";
import { auditActionLabel, auditGroupedCount, auditResourceLabel, auditTimestampValue, isGroupedBillingUsage } from "../lib/audit-display";

type R=Record<string,unknown>;

export function TenantOperationsPage({tenantId,operationId}:{tenantId:string;operationId?:string}){
 const root=`/api/tenants/${encodeURIComponent(tenantId)}/operations`;
 if(operationId)return <OperationDetail tenantId={tenantId} operationId={operationId}/>;
 const q=useApi<unknown>(root);const [search,setSearch]=useState("");const [status,setStatus]=useState("all");const rows=useMemo(()=>items<R>(q.data).filter(o=>{const hay=`${text(o.type,"")} ${text(o.status,"")} ${text(o.id,"")}`.toLowerCase();return(!search||hay.includes(search.toLowerCase()))&&(status==="all"||text(o.status,"")===status)}),[q.data,search,status]);const statuses=Array.from(new Set(items<R>(q.data).map(o=>text(o.status,"")).filter(Boolean)));
 return <main><PageHeader eyebrow="Tenant activity" title="Operations" description="Runtime, deployment and background jobs for this tenant."/><Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#E1E7F0] p-4 sm:flex-row"><div className="relative min-w-0 flex-1"><SearchIcon size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#718096]"/><TextInput className="pl-9" aria-label="Search operations" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search operations"/></div><Select aria-label="Operation status" className="sm:w-48" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</Select></div><DataTable embedded loading={q.loading} columns={[{key:"operation",label:"Operation"},{key:"status",label:"Status"},{key:"resource",label:"Resource"},{key:"time",label:"Updated"}]} rows={rows.map(o=>({key:idOf(o),href:tenantHref(tenantId,"operations",idOf(o)),cells:{operation:<strong>{text(o.type,"Operation").replaceAll("_"," ")}</strong>,status:<StatusText tone={statusTone(o.status)}>{text(o.status,"Unknown")}</StatusText>,resource:text(o.resourceName,text(o.appGroupName,text(o.resourceType,"—"))),time:formatDate(o.updatedAt??o.createdAt)}}))} empty={<EmptyState icon={<ActivityIcon/>} title="No operations" description="Background jobs and runtime actions will appear here."/>}/></Card></main>;
}

function OperationDetail({tenantId,operationId}:{tenantId:string;operationId:string}){
 const root=`/api/tenants/${encodeURIComponent(tenantId)}/operations/${encodeURIComponent(operationId)}`;const detail=useApi<R>(root);const events=useApi<unknown>(`${root}/events`);const [working,setWorking]=useState(false);const [error,setError]=useState<string>();async function retry(){setWorking(true);setError(undefined);try{await apiRequest(`${root}/retry`,{method:"POST"});await Promise.all([detail.reload(),events.reload()]);}catch(c){setError(c instanceof Error?c.message:"Operation could not be retried.");}finally{setWorking(false);}}const d=detail.data;return <main><PageHeader eyebrow="Operation detail" title={d?text(d.type,"Operation").replaceAll("_"," "):"Operation"} description="Runtime, deployment or background operation for this tenant." actions={<Button disabled={working} onClick={()=>void retry()}>{working?"Retrying…":"Retry operation"}</Button>}/>{error?<div className="mb-4"><Callout tone="danger" title="Retry failed">{error}</Callout></div>:null}<div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-5"><h2 className="font-semibold">Summary</h2>{detail.loading?<p className="mt-4 text-sm text-[#5B6678]">Loading operation…</p>:d?<dl className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><div><dt className="text-xs text-[#718096]">Status</dt><dd className="mt-1"><StatusText tone={statusTone(d.status)}>{text(d.status,"Unknown")}</StatusText></dd></div><div><dt className="text-xs text-[#718096]">Resource</dt><dd className="mt-1 text-sm font-medium">{text(d.resourceName,text(d.resourceType,"—"))}</dd></div><div><dt className="text-xs text-[#718096]">Created</dt><dd className="mt-1 text-sm">{formatDate(d.createdAt)}</dd></div><div><dt className="text-xs text-[#718096]">Updated</dt><dd className="mt-1 text-sm">{formatDate(d.updatedAt)}</dd></div></dl>:<p className="mt-4 text-sm text-[#B42318]">Operation unavailable.</p>}<a className="mt-5 inline-block text-sm font-semibold text-[#0F56A7] hover:underline" href={tenantHref(tenantId,"operations")}>Back to operations</a></Card><Card className="overflow-hidden"><div className="border-b border-[#E1E7F0] px-5 py-4"><h2 className="font-semibold">Events</h2></div><DataTable embedded loading={events.loading} columns={[{key:"event",label:"Event"},{key:"message",label:"Message"},{key:"time",label:"Timestamp"}]} rows={items<R>(events.data).map(e=>({key:idOf(e)||`${text(e.type)}-${text(e.createdAt)}`,cells:{event:<strong>{text(e.type,"Event").replaceAll("_"," ")}</strong>,message:text(e.message,text(e.detail,"—")),time:formatDate(e.createdAt)}}))} empty={<EmptyState icon={<ActivityIcon/>} title="No operation events" description="Progress events will appear here as the job runs."/>}/></Card></div></main>;
}

export function TenantAuditPage({tenantId}:{tenantId:string}){
 const base=`/api/tenants/${encodeURIComponent(tenantId)}/audit-log`;const [filters,setFilters]=useState({action:"",actor:"",resourceType:"",result:"",from:"",to:""});const query=useMemo(()=>{const p=new URLSearchParams();for(const [key,value] of Object.entries(filters))if(value)p.set(key,value);p.set("limit","100");return `${base}?${p}`;},[base,filters]);const q=useApi<unknown>(query);const rows=items<R>(q.data);function exportHref(format:"csv"|"json"){const p=new URLSearchParams();for(const [key,value] of Object.entries(filters))if(value)p.set(key,value);p.set("format",format);return `${base}/export?${p}`;}
 return <main><PageHeader eyebrow="Security history" title="Audit log" description="Search security and configuration changes by actor, resource, result and time range. Recurring billing usage is grouped in this view; CSV and JSON exports keep every raw audit event." actions={<div className="flex gap-2"><a className="inline-flex h-9 items-center rounded-md border border-[#C8D3E2] bg-white px-3 text-sm font-semibold text-[#354154] hover:bg-[#F5F8FC]" href={exportHref("csv")} download="audit-log.csv">Export CSV</a><a className="inline-flex h-9 items-center rounded-md border border-[#C8D3E2] bg-white px-3 text-sm font-semibold text-[#354154] hover:bg-[#F5F8FC]" href={exportHref("json")} download="audit-log.json">Export JSON</a></div>}/><Card className="mb-5 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-6"><Field label="Action"><TextInput value={filters.action} onChange={e=>setFilters({...filters,action:e.target.value})}/></Field><Field label="Actor"><TextInput value={filters.actor} onChange={e=>setFilters({...filters,actor:e.target.value})}/></Field><Field label="Resource type"><TextInput value={filters.resourceType} onChange={e=>setFilters({...filters,resourceType:e.target.value})}/></Field><Field label="Result"><TextInput value={filters.result} onChange={e=>setFilters({...filters,result:e.target.value})}/></Field><Field label="From"><TextInput type="datetime-local" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value?new Date(e.target.value).toISOString():""})}/></Field><Field label="To"><TextInput type="datetime-local" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value?new Date(e.target.value).toISOString():""})}/></Field></Card><Card className="overflow-hidden"><DataTable embedded loading={q.loading} columns={[{key:"action",label:"Action"},{key:"actor",label:"Actor"},{key:"resource",label:"Resource"},{key:"result",label:"Result"},{key:"time",label:"Timestamp"}]} rows={rows.map(a=>({key:idOf(a)||`${text(a.action)}-${text(auditTimestampValue(a))}`,cells:{action:<div><strong>{auditActionLabel(a)}</strong>{isGroupedBillingUsage(a)?<span className="mt-0.5 block text-xs font-normal text-[#718096]">{auditGroupedCount(a)} recurring usage events grouped</span>:null}</div>,actor:text(a.actorName,text(a.actorDisplayName,text(a.actorEmail,text(a.actor,"System")))),resource:<div><span>{auditResourceLabel(a)}</span>{!isGroupedBillingUsage(a)&&a.resourceName?<span className="block text-xs text-[#718096]">{text(a.resourceName)}</span>:null}</div>,result:<StatusText tone={statusTone(a.result)}>{text(a.result,"Unknown")}</StatusText>,time:formatDate(auditTimestampValue(a))}}))} empty={<EmptyState title="No audit records" description="No records match the current filters."/>}/></Card></main>;
}
